services:
  - type: web
    name: mini-blog
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn miniblog.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false 