services:
  - type: web
    name: mini-blog
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn miniblog.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: mini-blog-db
          property: connectionString
    staticPublishPath: ./staticfiles

databases:
  - name: mini-blog-db
    plan: free 